name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4 # python version is set default by .python-version file
        with:
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            flow/notify/requirements.txt
            requirements-dev.tx'

      - name: Install python packages
        run: make pip-install-dev

      - name: Run pre-commit
        run: make pre-commit
